terraform:

  # global level variables, these are supplied to all definitions
  terraform_vars:
    # a variable named: `deployment` is populated always, matching the name of the deployment passed on CLI
    region: {{ aws_region }}
    environment: dev

  definitions:
    tags:
      path: /definitions/tf12/misc-tags
    
    # network creates a VPC and required resources to launch instances
    network:
      path: /definitions/tf12/vpc-new/
      remote_vars:
        tags: tags.outputs.tag_map

    # deploy the wordpress app stack via cloudformation
    # why? because someone wants to use cloud formation!
    wordpress:
      path: /definitions/tf12/cf-wordpress
      terraform_vars:
        instance_type: t2.large
      remote_vars:
          tags: tags.outputs.tag_map
          vpc_id: network.outputs.vpc_id
          subnets: network.outputs.public_subnets

  # We're cleaning this up so providers/plugins isn't duplicated!
  providers:
    aws:
      vars:
        version: "~> 3.0"
        region: {{ aws_region }}
    'null':
      vars:
        version: "~> 3.0.0"
    random:
      vars:
        version: "~> 3.0"

  plugins:
    aws:
      version: 3.31.0
    'null':
      version: 3.0.0
    random:
      version: 3.1.0
